name: fcm_config
description: This flutter package is made to merge between firebase_messaging package and flutter_local_notifications 
version: 2.0.0-dev.9
homepage: https://github.com/mo-ah-dawood/fcm_config

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.1
  firebase_messaging: ^8.0.0-dev.11
  flutter_local_notifications: ^3.0.1+2