name: fcm_config
description: A new Flutter package project.
version: 1.0.0-beta.1
homepage: https://github.com/mo-ah-dawood/fcm_config

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^2.0.1